# -*- coding: utf-8 -*-
{
    'name': 'Anonymous Product Rating',
    'version': '17.0.1.0.0',
    'category': 'Website/eCommerce',
    'summary': 'Allow anonymous users to rate and comment on products with bot protection',
    'description': 'Anonymous Product Rating - Allow anonymous users to rate and comment on products with bot protection',
    'author': 'Isidoro Roa Saavedra',
    'website': 'https://www.softtechlatam.cl',
    'live_test_url': 'https://www.softtechlatam.cl/probar-gratis',
    'support': 'isidororoa@softtechlatam.cl',
    'depends': [
        'website_sale',
        'rating',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_config_parameter.xml',
        'data/cron_jobs.xml',
        'data/cleanup_corrupted_ratings.xml',
        'views/product_template_views.xml',
        'views/anonymous_rating_views.xml',
        'views/res_config_settings_views.xml',
        'views/performance_monitor_views.xml',
        'views/website_templates_clean.xml',
        'views/website_rating_override.xml',
        'views/website_rating_safe_access.xml',
        'views/website_product_rating_with_images.xml',
        'views/website_rating_integration.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'anonymous_product_rating/static/src/scss/anonymous_rating_images.scss',
            'anonymous_product_rating/static/src/js/anonymous_rating_images.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
